# https://docs.microsoft.com/en-us/rest/api/power-bi/
# 7f67af8a-fedc-4b08-8b4e-37c4d127b6cf = GlobalCloud PBI Desktop Client

@baseUrl = https://api.powerbi.com/v1.0/myorg
# @baseUrl = https://api.powerbi.com/beta/myorg

@groupId = 5176f617-bf38-4168-bed1-6072be7d332e
@datasetId = 08bb7318-0d74-4516-885a-ee4cb9d76fe4

####

# @name refreshes
POST {{baseUrl}}/groups/{{groupId}}/datasets/{{datasetId}}/refreshes
Authorization: Bearer {{$aadV2Token scopes:https://analysis.windows.net/powerbi/api/.default tenantId:tandg.global clientId:7f67af8a-fedc-4b08-8b4e-37c4d127b6cf}}
Content-Type: application/json

{
  "type": "Full",
  "commitMode": "PartialBatch",
  "applyRefreshPolicy": "False",
  "objects": [
    {
      "table": "Batch Master",
      "partition": "2022Q20531"
    },
    {
      "table": "Batch Master",
      "partition": "2022Q20531"
    }
  ]
}

# @refreshesLocation = {{refreshes.response.headers.Location}}
# @refreshId = 05086e06-a510-45d5-b7b5-8435ff61214a
@refreshId = {{refreshes.response.headers.RequestId}}

###

GET {{baseUrl}}/groups/{{groupId}}/datasets/{{datasetId}}/refreshes/{{refreshId}}
Authorization: Bearer {{$aadV2Token scopes:https://analysis.windows.net/powerbi/api/.default tenantId:tandg.global clientId:7f67af8a-fedc-4b08-8b4e-37c4d127b6cf}}

###

DELETE {{baseUrl}}/groups/{{groupId}}/datasets/{{datasetId}}/refreshes/{{refreshId}}
Authorization: Bearer {{$aadV2Token scopes:https://analysis.windows.net/powerbi/api/.default tenantId:tandg.global clientId:7f67af8a-fedc-4b08-8b4e-37c4d127b6cf}}

###

GET {{baseUrl}}/groups/{{groupId}}/datasets/{{datasetId}}/refreshes?$top=10
Authorization: Bearer {{$aadV2Token scopes:https://analysis.windows.net/powerbi/api/.default tenantId:tandg.global clientId:7f67af8a-fedc-4b08-8b4e-37c4d127b6cf}}
